# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml


  run-test:
    runs-on: ubuntu-latest
    steps:
      # Vérification usuelles
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # On execute les tests sans interruption
      - name: Run tests
        run: mvn clean test
        continue-on-error: true
        
      - run: touch /.github/workflow/test-report
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: /.github/workflow/

      - name: Check if tests passed
        if: ${{ failure() }}
        run: echo "::error line=1::Test check failed" && exit 1

  coverages:
    runs-on: ubuntu-latest
    needs: run-test #Action nécessaire à exécuter avant
    steps:
    # Vérification usuelles
      - name: Checkout repository
        uses: actions/checkout@v4
        # Installation de JAVA
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: test-report
          path: /.github/workflow/

      
      - name: Run tests with Maven and generate coverage report
        run: mvn clean test jacoco:report
      - run: rm test-report
      - name: Check code coverage
        id: check-coverage
        run: mvn clean verify jacoco:report || echo "::error line=1::Coverage checks have not been met" && exit 1
