name: Run JUnit tests

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      # Vérification usuelles
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # On execute les tests sans interruption
      - name: Run tests
        run: mvn clean test
        continue-on-error: true

      - name: Check if tests passed
        if: ${{ failure() }}
        run: echo "::error line=1::Test check failed" && exit 1

  coverages:
    runs-on: ubuntu-latest
    steps:
    # Vérification usuelles
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests with Maven and generate coverage report
        run: mvn clean test jacoco:report

      - name: Check code coverage
        id: check-coverage
        run: mvn clean verify jacoco:report || echo "::error line=1::Coverage checks have not been met" && exit 1
